[package]
name = "links_it_in_dublin"
version = "0.1.0"
authors = ["Lucas Oliveira <loliveira@cartrawler.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
actix-files = "0.4.0"
comrak = "0.6.2"